config/routes.rb
Rails.application.routes.draw do
  root 'cachorros#index'

  resources :cachorros
end

app/models/cachorro.rb
class Cachorro < ActiveRecord::Base
  GENEROS = %w(femea macho)

  validates :raca, presence: true
  validates :genero, inclusion: { in: GENEROS }
  validates :data_nascimento, presence: true
  validates :nome, presence: true
  validates :nome_dono, presence: true
  validates :telefone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cachorros_controller.rb
class CachorrosController < ApplicationController
  def index
    @search = CachorroSearch.new cachorro_search_params
    @cachorros  = @search.search
  end

  private

  def cachorro_search_params
    search_params = params.include?(:cachorro_search) ? params.require(:cachorro_search).permit(:query, :field, :order, :page) : {}
    search_params.merge(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cachorros/index.html.erb
<%= form_for @search, url: cachorros_url, html: {method: "GET"} do |f| %>

  <h1><%= t(".cachorros") %></h1>

  <div class="row padding-top-20">
    <div class="col-xs-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-xs-10">
            <%= f.text_field :query, placeholder: t(".buscar"), class: "form-control" %>
          </div>
          <div class="col-xs-2">
            <%= f.select :field, options_for_select(@search.field_options, @search.field), {}, class: "form-control" %>
          </div>
          <br/><br/><br/>
          <div class="col-xs-5">
            <div class="col-xs-2">
              <%= f.label t(".ordem"), class: 'label-inline' %>
            </div>
            <div class="col-xs-6">
              <%= f.select :order, options_for_select(@search.order_options, @search.order), {}, class: "form-control", data: {"submit-on-change" => true} %>
            </div>
          </div>
          <div class="col-xs-7">
            <div class="col-xs-2 col-xs-offset-8">
              <%= f.submit t('.buscar'), class: 'btn btn-info col-xs-12' %>
            </div>
            <div class="col-xs-1">
              <%= link_to t(".limpar"), cachorros_path, class: 'btn btn-default' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <table class="table table-striped">
      <tr>
        <th><%= t("activerecord.attributes.cachorros.nome_dono") %></th>
        <th><%= t("activerecord.attributes.cachorros.telefone") %></th>
        <th><%= t("activerecord.attributes.cachorros.nome") %></th>
        <th><%= t("activerecord.attributes.cachorros.raca") %></th>
        <th><%= t("activerecord.attributes.cachorros.genero") %></th>
        <th><%= t("activerecord.attributes.cachorros.castrado") %></th>
        <th><%= t("activerecord.attributes.cachorros.data_nascimento") %></th>
        <th><%= t("activerecord.attributes.cachorros.ultima_consulta") %></th>
      </tr>
      <% @cachorros.each do |cachorro| %>
        <tr>
          <td><%= cachorro.nome_dono %></td>
          <td><%= cachorro.telefone %></td>
          <td><%= cachorro.nome %></td>
          <td><%= cachorro.raca %></td>
          <td><%= t("global.cachorro.genero.#{cachorro.genero}") %></td>
          <td><%= cachorro.castrado ? t("global.cachorro.castrado.sim") : t("global.cachorro.castrado.nao") %></td>
          <td><%= cachorro.data_nascimento.strftime("%d/%m/%Y") %></td>
          <td><%= cachorro.data_ultima_consulta.strftime("%d/%m/%Y") %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-5"><%= paginate @cachorros %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetShop</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <div id="page-wrapper">
        <div class="wrapper wrapper-content">
          <div class="container">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>